### ISSUE TITLE
update docs for Custom Scrapers

### ISSUE THREAD

**Issue by wearpants** [opensyllabus/osp-scraper#11]
Please add a section to README with a high-level overview of how to write a custom scraper. Stuff like:
1. work on a branch named `scraper/<site_name>`. Each branch should contain a single site.
2. save your new scraper in `syllascrape/spiders/<site_name>.py`
3. Inherit from class `CustomSpider` and implement methods `x(), y(), z()`

**Comment by jodizzle** [comment]
Duplicate of #81.
Closing in favor of newer issue.
