### ISSUE TITLE
Make `--local` option in crawl scripts work when running multiple crawls

### ISSUE THREAD

**Issue by jodizzle** [opensyllabus/osp-scraper#149]
In theory, the `--local` option for crawl scripts like `edu_repo_crawler` should run crawls sequentially and without the need for a redis server.  However, it seems like after the first crawl completes, twisted crashes with a `twisted.internet.error.ReactorNotRestartable` error right after starting the next crawl.

[This SO post](https://stackoverflow.com/questions/41495052/scrapy-reactor-not-restartable/43661172#43661172) seems relevant.

**Comment by wearpants** [comment]
Yup, we used to support this under celery but it got taken out
